export { default as Dashboard } from "./Dashboard/Dashboard";
export { default as Login } from "./Login/Login";
export { default as SignUp } from "./SignUp/SignUp";
export { default as About } from "./About/About";
export { default as Blog } from "./Blog/Blog";
export { default as Contact } from "./Contact/Contact";
export { default as Pricing } from "./Pricing/Pricing";
export { default as Services } from "./Services/Services";
export { default as AdminPanel } from "./AdminPanel/AdminPanel";
